# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Running Jenkins Job!
  displayName: 'Jenkins Queue Job'

- task: JenkinsQueueJob@2
  inputs:
    serverEndpoint: 'JenkinsSC01_Demo'
    jobName: 'sayeda-project1'
    captureConsole: true
    capturePipeline: true
    isParameterizedJob: false
-
